import Foundation

enum Strings {
    enum App {
        static let name = "Anicca"
        static let tagline = "Read your energy. Understand yourself."
    }

    enum Auth {
        static let welcomeTitle = "Welcome to Anicca"
        static let welcomeSubtitle = "Sign in to start tracking your inner weather."
        static let continueWithApple = "Continue with Apple"
        static let continueWithGoogle = "Continue with Google"
        static let signIn = "Sign In"
        static let signUp = "Sign Up"
        static let email = "Email"
        static let password = "Password"
        static let confirmPassword = "Confirm Password"
        static let displayName = "Display Name"
        static let forgotPassword = "Forgot password?"
        static let noAccountPrompt = "Don't have an account? Sign up"
        static let hasAccountPrompt = "Already have an account? Sign in"
        static let or = "or"
        static let resetSent = "Password reset email sent. Check your inbox."
        static let invalidEmail = "Enter a valid email address."
        static let passwordTooShort = "Password must be at least 8 characters."
        static let passwordsDoNotMatch = "Passwords do not match."
        static let displayNameRequired = "Please enter a display name."
    }

    enum Onboarding {
        static let step1Title = "Your inner world has a map."
        static let step1Body = "Anicca helps you tune in to seven distinct centers of energy — each one a layer of how you feel, think, and move through the day."
        static let step2Title = "The 7 Centers"
        static let step2Body = "Each center represents a different aspect of your experience. Tap a center to learn more."
        static let step3Title = "How check-ins work"
        static let step4Title = "Gentle reminders"
        static let step4Body = "We'll nudge you once a day to check in. No streaks to chase — just a soft invitation to listen."
        static let enableReminders = "Enable Reminders"
        static let maybeLater = "Maybe Later"
        static let next = "Next"
        static let skip = "Skip"
        static let getStarted = "Get Started"
    }

    enum Log {
        static let title = "How are you feeling?"
        static let subtitle = "Tap the emotions that resonate with you right now"
        static let searchPlaceholder = "Search emotions"
        static let expandAll = "Expand All"
        static let collapseAll = "Collapse All"
        static let intensityTitle = "How strongly?"
        static let notePlaceholder = "Add a note... (optional)"
        static let saveCheckIn = "Save Check-in"
        static let cancel = "Cancel"
        static let savedToast = "Check-in saved ✦"
        static let freeLimitWarning = "You have %d free check-ins left this month."
        static let freeLimitReached = "You've reached your monthly limit. Upgrade to keep logging."
    }

    enum Insights {
        static let title = "Insights"
        static let radarTitle = "Chakra Balance"
        static let radarSubtitle = "Center = blocked · Middle = balanced · Outer = overactive"
        static let weeklySummary = "Weekly Summary"
        static let aiInsightTitle = "Your weekly insight"
        static let aiInsightLocked = "Upgrade to Pro to get weekly AI-generated reflections based on your patterns"
        static let aiInsightUnlock = "Unlock with Pro →"
        static let aiInsightCaption = "Generated by Gemini ✦"
        static let recentCheckIns = "Recent Check-ins"
        static let emptyState = "Start logging to see your balance"
        static let timeline = "Mood Timeline"
        static let centersBreakdown = "Energy Centers"
    }

    enum Settings {
        static let title = "Settings"
        static let account = "Account"
        static let subscription = "Subscription"
        static let reminders = "Reminders"
        static let dataExport = "Data & Export"
        static let integrations = "Integrations"
        static let about = "About"
        static let exportJSON = "Export as JSON"
        static let exportPDF = "Export as PDF"
        static let openYggdrasil = "Open in Yggdrasil →"
        static let yggdrasilCaption = "Deep sync coming soon"
        static let privacy = "Privacy Policy"
        static let terms = "Terms of Use"
        static let rate = "Rate Anicca"
        static let deleteAccount = "Delete My Account"
        static let manageSubscription = "Manage Subscription"
        static let upgradeToPro = "Upgrade to Pro"
        static let reminderToggle = "Daily check-in reminder"
        static let proFeature = "Pro feature"
        static let signOut = "Sign Out"
    }

    enum Paywall {
        static let headline = "Unlock Your Full Pattern"
        static let subheadline = "Get AI-powered insights, unlimited check-ins, and deeper self-awareness."
        static let monthly = "Monthly"
        static let annual = "Annual"
        static let saveBadge = "Save 33%"
        static let startPro = "Start Pro"
        static let getBundle = "Get the Bundle"
        static let restore = "Restore Purchases"
        static let footer = "Cancel anytime. Billed through the App Store."
        static let purchaseCancelled = "Purchase cancelled."
        static let networkError = "Check your connection and try again."
        static let purchaseFailed = "Purchase failed. Please try again."
        static let restoreSuccess = "Purchases restored."
        static let nothingToRestore = "No previous purchases found."
    }

    enum Errors {
        static let generic = "Something went wrong. Please try again."
        static let network = "We can't reach the network right now."
        static let auth = "We couldn't sign you in. Please check your credentials."
        static let aiUnavailable = "Insights are taking a moment. Try again shortly."
    }
}
